### ISSUE TITLE
다국어 관리자의 Column 고정 기능 추가

### ISSUE THREAD

**Issue by GukhyeonRyu** [dannyldj/ResxManagerExtended#16]
Column 고정 기능이 있으면 좋을 것 같습니다.
선택해서 고정할 수 있다면 가장 좋겠으나, 안된다면 `Key` Column 정도는 수평 Scroll을 사용해도 항상 볼 수 있으면 좋겠습니다.

**Comment by dannyldj** [comment]
DataGrid에서 지원하지 않는 기능이기 때문에 추후 Fluent 라이브러리가 업데이트 된다면 고려하겠습니다
